package com.excilys.excilysbanking.webservices.soap.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import com.excilys.excilysbanking.webservices.soap.CompteServiceWS;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-07-05T15:36:11.396+02:00
 * Generated source version: 2.6.1
 * 
 */
@WebServiceClient(name = "CompteServiceWSImplService", 
                  wsdlLocation = "http://localhost:8080/ebankWS-soap/services/CompteServiceWS?wsdl",
                  targetNamespace = "http://impl.soap.webservices.excilysbanking.excilys.com/") 
public class CompteServiceWSImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.soap.webservices.excilysbanking.excilys.com/", "CompteServiceWSImplService");
    public final static QName CompteServiceWSImplPort = new QName("http://impl.soap.webservices.excilysbanking.excilys.com/", "CompteServiceWSImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/ebankWS-soap/services/CompteServiceWS?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CompteServiceWSImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/ebankWS-soap/services/CompteServiceWS?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CompteServiceWSImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CompteServiceWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CompteServiceWSImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns CompteServiceWS
     */
    @WebEndpoint(name = "CompteServiceWSImplPort")
    public CompteServiceWS getCompteServiceWSImplPort() {
        return super.getPort(CompteServiceWSImplPort, CompteServiceWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CompteServiceWS
     */
    @WebEndpoint(name = "CompteServiceWSImplPort")
    public CompteServiceWS getCompteServiceWSImplPort(WebServiceFeature... features) {
        return super.getPort(CompteServiceWSImplPort, CompteServiceWS.class, features);
    }

}
