package com.excilys.excilysbanking.webservices.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-07-05T15:36:11.361+02:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://soap.webservices.excilysbanking.excilys.com/", name = "CompteServiceWS")
@XmlSeeAlso({ObjectFactory.class})
public interface CompteServiceWS {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllComptes", targetNamespace = "http://soap.webservices.excilysbanking.excilys.com/", className = "com.excilys.excilysbanking.webservices.soap.GetAllComptes")
    @WebMethod
    @ResponseWrapper(localName = "getAllComptesResponse", targetNamespace = "http://soap.webservices.excilysbanking.excilys.com/", className = "com.excilys.excilysbanking.webservices.soap.GetAllComptesResponse")
    public java.util.List<com.excilys.excilysbanking.webservices.soap.CompteDTO> getAllComptes();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCompteById", targetNamespace = "http://soap.webservices.excilysbanking.excilys.com/", className = "com.excilys.excilysbanking.webservices.soap.GetCompteById")
    @WebMethod
    @ResponseWrapper(localName = "getCompteByIdResponse", targetNamespace = "http://soap.webservices.excilysbanking.excilys.com/", className = "com.excilys.excilysbanking.webservices.soap.GetCompteByIdResponse")
    public com.excilys.excilysbanking.webservices.soap.CompteDTO getCompteById(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Integer arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getComptesByUsername", targetNamespace = "http://soap.webservices.excilysbanking.excilys.com/", className = "com.excilys.excilysbanking.webservices.soap.GetComptesByUsername")
    @WebMethod
    @ResponseWrapper(localName = "getComptesByUsernameResponse", targetNamespace = "http://soap.webservices.excilysbanking.excilys.com/", className = "com.excilys.excilysbanking.webservices.soap.GetComptesByUsernameResponse")
    public java.util.List<com.excilys.excilysbanking.webservices.soap.CompteDTO> getComptesByUsername(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
